#!/usr/bin/env bash

# Taps
tap 'caskroom/cask'

# Install GNU core utilities (those that come with macOS are outdated)
brew 'coreutils'
brew 'cmake'

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew 'findutils'

# Install some other useful utilities like `sponge`.
brew 'moreutils'

# Install Bash 4
brew 'bash'
brew 'tmux'

# Install Binaries
brew 'git'
brew 'wget'
brew 'vim'

# Install GnuPG to enable PGP-signing commits.
brew 'gnupg'

# Install more recent versions of some macOS tools.
brew 'openssh'
brew 'grep'
brew 'openssl'
brew 'pkg-config'
brew 'python3'

# Install yarn, a JavaScript package manager
brew 'yarn'

brew 'zsh'
brew 'zsh-completions'
brew 'z'
brew 'composer'
brew 'mas'
brew 'hub'

# Apps
cask 'atom'
cask 'docker'
cask 'google-chrome'
cask 'github'
cask 'slack'
cask 'spotify'
cask 'sublime-text'
cask 'iterm2'
cask 'postman'
cask 'visual-studio-code'


# Install Mac App Store apps
#mas 'trello'
#mas 'magnet'

