cask "1password", greedy: true
cask "chatgpt", greedy: true
cask "claude", greedy: true
cask "cursor", greedy: true
cask "docker-desktop", greedy: true
cask "element", greedy: true
cask "firefox", greedy: true
cask "google-chrome", greedy: true
cask "zed", greedy: true
cask "figma", greedy: true
cask "signal", greedy: true
cask "font-hack-nerd-font", greedy: true
cask "ghostty", greedy: true
cask "obsidian", greedy: true
cask "spotify", greedy: true
cask "tailscale-app", greedy: true
cask "visual-studio-code", greedy: true
