cask "1password", greedy: true
cask "chatgpt", greedy: true
cask "claude", greedy: true
cask "cursor", greedy: true
cask "element", greedy: true
cask "ghostty", greedy: true
cask "obsidian", greedy: true
cask "spotify", greedy: true
cask "tailscale-app", greedy: true
cask "visual-studio-code", greedy: true
