cask "1password", greedy: true
cask "1password-cli", greedy: true
cask "chatgpt", greedy: true
cask "claude", greedy: true
cask "claude-code", greedy: true
cask "codex", greedy: true
cask "cursor", greedy: true
cask "cursor-cli", greedy: true
cask "docker-desktop", greedy: true
cask "element", greedy: true
cask "font-hack-nerd-font", greedy: true
cask "ghostty", greedy: true
cask "obsidian", greedy: true
cask "spotify", greedy: true
cask "tailscale-app", greedy: true
cask "visual-studio-code", greedy: true
